### ISSUE TITLE
SELECT ALL - NO LONGER WORKS

### ISSUE THREAD

**Issue by stampday** [RealRaven2000/quickFilters#165]
SELECT ALL - NO LONGER WORKS

**Comment by RealRaven2000** [comment]
This is a quickFilters issue, so I transferred it here. This has already been reported in issue #160 and fixed by me yesterday. Please open Thunderbird Add-ons Manager and click on "check for updates".

![image](https://user-images.githubusercontent.com/6314674/219943500-de5e6d8b-4bb2-4924-b729-21320e3e690f.png)

**Comment by stampday** [comment]
there was no update for tb 90 so i am still unable to select all also the ctrl+a keys does something weird

**Comment by RealRaven2000** [comment]
that's strange. what version of quickFilters do you run? As far as I know the problem is in 5.8 and that has minver = 91 and thus cannot be installed in Thunderbird 90

**Comment by RealRaven2000** [comment]
If you are running 5.8 on Thunderbird 90 (ESR = current version  = is 91) can you go back to version 5.6 to see if that works? If you're running 5.7.1 I will have to look what can be done, but I am afraid I cannot make code backwards compatible to 78 (pre91). I might be possible to support 90, but I think that's a beta version??

**Comment by RealRaven2000** [comment]
you can find out your current quickFilters version number by right-clicking the assistant button. it's on the top of the quickFilters preferences window:

![image](https://user-images.githubusercontent.com/6314674/219954926-cfe559a5-db52-41d3-a7f9-ad36ddcdcb61.png)

**Comment by RealRaven2000** [comment]
Fixed in 5.8.1 (compatible with Thunderbird 91.0 and higher) released on 18/02/2023
